### ISSUE TITLE
Community update available  - New maintained plugin

### ISSUE THREAD

**Issue by EYALIN** [apache/cordova-plugin-battery-status#107]
unfortunately, this plugin creator @apache , did fantastic work, and we highly appreciate him not maintaining this plugin anymore (not responding for a while).
we moved to a maintained plugin (which forked from this one) to here:
https://github.com/EYALIN/community-cordova-plugin-battery-status

you can install it as an npm package:
cordova plugin add community-cordova-plugin-battery-status --save

**Comment by breautek** [comment]
Posting an announcement like this here is not really appropriate. Please use [Discussions](https://github.com/apache/cordova/discussions) instead.

issues should be reserved for... issues.
