### ISSUE TITLE
Android version update ERROR

### ISSUE THREAD

**Issue by yecicen** [apache/cordova-plugin-battery-status#68]
We get this error below after started to use Android 7.x. We read the documentation (https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html) bu we still have no solution. Can you help us, please ?

Installing "cordova-plugin-battery-status" for android
Failed to install 'cordova-plugin-battery-status': Error: ENOENT: no such file or directory, open '/Users/apple/Desktop/simplyPOD/platforms/android/AndroidManifest.xml'

**Comment by janpio** [comment]
Are you installing the newest version of the plugin?
What are all your other versions (Cordova CLI, Cordova-Android etc)?

**Comment by thienban** [comment]
i have a same error when update to cordova CLI 8.0.0 with cordova-android 7.0

**Comment by jcesarmobile** [comment]
This was a cordova-android bug, should be fixed on 7.1.4.
